version: "3.4"

services:

    worker:
        image: 127.0.0.1:5000/cluster/worker
        networks:
            - cluster_backend
        deploy:
            replicas: 5

networks:
    cluster_backend:
        external: true
