version: "3.4"

services:

    manager:
        image: 127.0.0.1:5000/cluster/manager
        build:
            context: .
            dockerfile: cmd/manager/Dockerfile
        volumes:
            - .:/go/src/github.com/duhruh/cluster
        depends_on:
            - rabbit-manage
        networks:
            - backend

    worker:
        image: 127.0.0.1:5000/cluster/worker
        build:
            context: .
            dockerfile: cmd/worker/Dockerfile
        volumes:
            - .:/go/src/github.com/duhruh/cluster
        depends_on:
            - rabbit-manage
        networks:
            - backend
        deploy:
            replicas: 4

    rabbit-manage:
        image: 127.0.0.1:5000/rabbitmq:management
        ports:
            - "15672:15672"
        networks:
            - backend

    file-server:
        image: nginx
        volumes:
            - /media/pi/72B7-554A:/usr/share/nginx/html:ro
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - backend


networks:
    backend:
        driver: overlay
        attachable: true
