version: "3.4"
services:
        app:
                build: .
                volumes:
                        - .:/go/src/github.com/duhruh/cluster
                depends_on:
                        - rabbit-manage
                networks:
                        - backend
                          #        rabbit:
                          #                image: rabbitmq
                          #                ports:
                          #                        - "5672:5672"
                          #                        - "15672:15672"
        rabbit-manage:
                image: rabbitmq:management
                ports:
                        - "15672:15672"
                networks:
                        - backend
networks:
        backend:
                driver: "bridge"
